extends: "eslint:recommended"

parserOptions:
  ecmaVersion: 6
  sourceType: module

env:
  browser: true
  node: true

rules:
  no-undef: 0
  no-console: 0
  quotes: ['error', 'single']
  curly: ['error', 'all']
  default-case: 'error'
  vars-on-top: 'error'
  one-var: ['error', 'always']
  brace-style: ['error', '1tbs']
  camelcase: ['error', {properties: "never"}]
  comma-dangle: ['error', {after: true, before: false}]
  comma-spacing: ['error', {after: true, before: false}]
  comma-style: ['error', 'last']
  spaced-comment: ['error', 'always']
  space-unary-ops: 'error'
  space-infix-ops: 'error'
  space-in-parens: ['error', 'never']
  space-before-blocks: 'error'
  semi-spacing: ['error', {before: false, after: true}]
  keyword-spacing: ['error', {after: true, before: true}]
  no-trailing-spaces: 'error'
  no-unneeded-ternary: 'error'
  no-multiple-empty-lines: ['error', {max: 1}]
  newline-per-chained-call: ['error', {ignoreChainWithDepth: 2}]
  newline-before-return: 'error'
  newline-after-var: ['error', 'always']
  multiline-ternary: ['error', 'never']
  max-params: ['error', 3]
  max-nested-callbacks: ['error', 3]
  lines-around-directive: ['error', 'always']
  lines-around-comment: ['error', {beforeBlockComment: true}]
  linebreak-style: ['error', 'unix']
  line-comment-position: ['error', {position: 'above'}]
  key-spacing: ['error', {beforeColon: false, afterColon: true, mode: 'strict'}]
  indent: ['error', 4]
  func-style: ['error', 'expression']
  func-call-spacing: ['error', 'never']
  eol-last: ['error', 'always']
  consistent-this: ['error', 'that']
